In [2]:
import numpy as np

QUESTION 1:

In [3]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A.shape

(2, 3)

QUESTION 2:

In [4]:
A = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15]])
print(A[1, 2: 4])

[8 9]


QUESTION 3:

In [6]:
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])
B = A[:, 2]
B

array([ 3,  7, 11, 15])

QUESTION 4:

In [8]:
A = np.array([[1, 1, 2, 3],
              [4, 5, 1, 4],
              [1, 9, 10, 11]])

print(A.sum(axis = 0))

[ 6 15 13 18]


QUESTION 5:

In [9]:
A = np.array(([1, 2, 3]))
B = np.array([[4, 5, 6]])
print(A + B)

[[5 7 9]]


QUESTION 6:

In [12]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(x @ y)

32


In [13]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(x * y)

[ 4 10 18]


In [14]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(np.dot(x, y))

32


In [15]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(np.sum(x * y))

32


QUESTION 7:

In [16]:
w = np.zeros(5)
w = w + 2
print(w)

[2. 2. 2. 2. 2.]


QUESTION 8:

In [17]:
x = np.linspace(-1, 1, 5)
y = 2 * x + 4
print(y)

[2. 3. 4. 5. 6.]


QUESTION 9:

In [23]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8], [9, 10], [11, 12]])
result = x @ y
print(result)

[[ 58  64]
 [139 154]]


QUESTION 10:

In [25]:
A = np.array([[1, 2], [1, 3], [1, 5]])
x = np.array([1, 2])
b = np.array([3, 4, 5])

A * x - b

ValueError: ignored

In [24]:
A = np.array([[1, 2], [1, 3], [1, 5]])
x = np.array([1, 2])
b = np.array([3, 4, 5])
A @ x - b

array([2, 3, 6])

QUESTION 11:

In [26]:
M = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
b = np.array([1, 2, 3, 4])
b = np.expand_dims(b, axis = 1)
M + b

ValueError: ignored

In [27]:
M = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
b = np.array([1, 2, 3, 4])
M + b

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12],
       [10, 12, 14, 16]])

QUESTION 12:

In [28]:
M = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
b = np.array([1, 2, 3])
b = np.expand_dims(b, axis = 1)
M + b

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10],
       [12, 13, 14, 15]])

In [29]:
M = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
b = np.array([1, 2, 3])
M + b

ValueError: ignored